---

- name: Nginx container
  docker:
    name: nginx
    image: nginx:latest
    #command: mkdir /etc/nginx/ssl && chmod  600 /etc/nginx/ssl
    state: started
    ports:
      - "80:80"
  tags: nginx
