---
- name: Remove old versions of Docker
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-common
    - docker-selinux
    - docker-engine
  tags: docker-centos

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
  tags: docker-centos

- name: Add Docker GPG key.
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present
  tags: docker-centos

- name: Add Docker repository.
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: '/etc/yum.repos.d/docker-ce.repo'
    owner: root
    group: root
    mode: 0644
  tags: docker-centos

- name: install Docker
  yum:
    name: docker-ce
    state: latest
  tags: docker-centos

- name: Make sure Docker is running
  service:
    name: docker
    state: running
  tags: docker-centos

- name: Check current docker-compose version.
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false
  tags: docker-centos

- name: Delete existing docker-compose version if it's different.
  file:
    path: /usr/local/bin/docker-compose
    state: absent
  when: >
    docker_compose_current_version.stdout is defined
    and docker_compose_version not in docker_compose_current_version.stdout
  tags: docker-centos

- name: Install Docker Compose (if configured).
  get_url:
    url: https://github.com/docker/compose/releases/download/1.17.1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
  tags: docker-centos
