---
- name: Update Package list
  apt:
    update_cache: yes
  tags: docker-debian

- name: Upgrade packages
  apt:
    upgrade: safe
  tags: docker-debian

- name: Uninstall old versions of docker
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io
  tags: docker-debian
